version: 0.1.{build}

image:
  - Visual Studio 2019

platform:
  - x64

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11\

init:
  - ver
  - ps: $env:Path = $env:JAVA_HOME + "bin\;" + $env:Path
  - java -version

build_script:
  - ps: ./gradlew jar

artifacts:
  - path: build/libs/curvedetect.jar
    name: curvedetect.jar
