name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-jar:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build fat-jar
        run: ./gradlew jar
      - name: Upload fat-jar
        uses: actions/upload-artifact@v2
        with:
          name: curvedetect-win.jar
          path: build/libs/curvedetect.jar

  build-native:
    name: Build native image for Windows

    runs-on: windows-latest

    env:
      GRAALVM_HOME: C:\hostedtoolcache\windows\GraalVM\java11-windows-amd64-21.0.0.2\x64\

    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.0.0.2

      - name: Set up Visual Studio x64 shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Build image
        run: ./gradlew nativeBuild

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          file: ./build/client/x86_64-windows/curvedetect.exe
          args: --best -fq

      - name: Upload native-image
        uses: actions/upload-artifact@v2
        with:
          name: curvedetect-x86_64.exe
          path: build/client/x86_64-windows/curvedetect.exe
